#!/bin/bash
# appeler au lieu de coq_makefile
#
$COQBIN/coq_makefile \
	-I prelude/ -I rpo -I epsilon0 -I gamma0 -I misc \
	prelude/*.v rpo/*.v epsilon0/*.v gamma0/*.v misc/*.v \
	-custom 'rm -f docdir/*.html; $(COQDOC) --glob-from htmllinks \
   	$(VFILES)' '$(VFILES)' docu \
| sed  s/'COQC=$(COQBIN)coqc'/'COQC=\$(COQBIN)coqc -dump-glob htmllinks'/ |  \
 sed  s/'COQDOC=$(COQBIN)coqdoc'/'COQDOC=$(COQBIN)coqdoc -g -d docdir --glob-from htmllinks -R `pwd` Ordinals '/ |  \
 sed s/'rm -f all.ps'/'rm -f htmllinks all.ps'/ \
	> Makefile